groups: []
resources:
- name: charts
  type: git
  source:
    branch: master
    uri: https://github.com/helm/charts
- name: ci
  type: git
  source:
    branch: k8s # TODO master
    uri: https://github.com/govau/deploy-awsbroker
    path:
    - k8s/**
- name: service-catalog.release
  type: github-release
  source:
    access_token: ((github-public-repo-personal-access-token))
    owner: kubernetes-incubator
    repository: service-catalog
# - name: slack
#   type: slack-notification
#   source:
#     url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: deploy-ci
  serial_groups:
  - ci
  plan:
  - do:
    - get: charts
    - get: service-catalog.release
    - get: ci
    - task: deploy
      file: ci/k8s/deploy.yml
      params:
        HELM_PREFIX: ci-
        NAMESPACE: aws-sb-ci
    - task: smoke-test
      file: deploy-src/k8s/smoke-test.yml
      params:
        NAMESPACE: aws-sb-ci
- name: delete-ci
  serial_groups:
  - ci
  plan:
  - do:
    - get: ci
      passed:
      - deploy-ci
      trigger: true
    - task: delete
      file: deploy-src/k8s/delete.yml
      params:
        NAMESPACE: sentry-ci
