---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: govau/cga-cf-bosh-cli
    tag: latest
inputs:
- name: deploy-src

params:
  KUBECONFIG:
  NAMESPACE:

run:
  path: deploy-src/k8s/smoke-test.sh
